---
- name: Create core namespaces
  command:
    cmd: kubectl create namespace {{ item }}
  loop:
    - gotify
    - monitoring
    - mqtt
    - plex
    - smokeping
    - syncthing
    - transmission
    - vaultwarden
    - www
  register: ns_create
  changed_when: "'created' in ns_create.stdout or ns_create.rc == 0"
  failed_when: "ns_create.rc != 0 and 'already exists' not in ns_create.stderr"
