apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photos-postgres-data
  namespace: photos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photos-minio-data
  namespace: photos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
